In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('students_placement.csv')

In [3]:
df.shape

(300, 4)

In [4]:
df.sample(5)

     cgpa   iq  profile_score  placed
272  5.94  108             28       0
47   8.09   97             80       1
157  5.19  108             69       0
191  5.34  104             98       0
2    6.60  110             61       0

In [5]:
X = df.drop(columns=['placed'])
y = df['placed']

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [7]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
scaler = StandardScaler()
X_train_trf = scaler.fit_transform(X_train)
X_test_trf = scaler.transform(X_test)
accuracy_score(y_test,
               LogisticRegression()
               .fit(X_train_trf,y_train)
               .predict(X_test_trf))

0.8833333333333333

In [8]:
from sklearn.ensemble import RandomForestClassifier
accuracy_score(y_test,RandomForestClassifier().fit(X_train,y_train).predict(X_test))

0.8833333333333333

In [9]:
from sklearn.svm import SVC
accuracy_score(y_test,SVC(kernel='rbf').fit(X_train,y_train).predict(X_test))

0.9333333333333333

In [10]:
svc = SVC(kernel='rbf')
svc.fit(X_train,y_train)

SVC()

In [11]:
rf = RandomForestClassifier()
rf.fit(X_train,y_train)

RandomForestClassifier()

In [12]:
import pickle 
pickle.dump(svc,open('model.pkl','wb'))

In [13]:
rf.predict(np.array([4.5,56,10]).reshape(1,3))

C:\Users\91957\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

array([1], dtype=int64)

In [14]:
import joblib

In [16]:
joblib.dump(rf,"placement_predictor.joblib")

['placement_predictor.joblib']

In [18]:
model=joblib.load('placement_predictor.joblib')

In [19]:
X_train

     cgpa   iq  profile_score
66   6.42  115             59
163  5.52  116             58
205  6.70  102             58
53   8.43   88             42
246  6.14  110             57
..    ...  ...            ...
75   5.76  108             64
22   7.36  105             77
72   6.15   85             63
15   7.88   91             59
168  8.12   94             72

[240 rows x 3 columns]

In [20]:
X_test

     cgpa   iq  profile_score
98   7.27   91             70
259  5.13  114             54
184  8.49   89             70
256  7.65   98             50
29   7.21   96             94
254  7.34   97             51
7    7.97   86            100
13   7.74   96             72
230  9.05   94             67
91   4.94  104             82
284  7.06   93             44
127  6.65  106             45
30   5.99  113             59
241  8.56  102             63
113  8.25   92             67
84   7.01   97             59
99   8.11   95             60
140  6.34  105             65
144  7.01   99             64
94   7.08   99             61
35   5.50  112             54
3    5.54  113             68
173  7.22   94             58
175  6.40  105             55
215  7.00  104             48
89   5.83  110             68
203  8.47   87             72
193  8.37  107             58
266  7.26  110             56
281  7.60  103             64
131  7.08   95             43
209  7.24   95             66
271  7.03   97             50
161  6.11  111             44
176  4.60  116             71
174  7.81   95             59
245  8.52   99             58
289  5.83  104             51
74   7.49   88             47
109  6.23  113             65
155  6.68  110             50
65   8.41  100             58
41   6.05  106             94
11   5.64  106             36
293  6.86  110             63
240  7.49   95             64
130  6.69   93             72
114  5.89  108             72
77   7.11   97             49
171  8.71   88             58
235  5.12  105             68
272  5.94  108             28
134  6.58  113             57
214  5.80  107             92
151  5.70  118             65
10   7.64  102             51
159  5.84  105             67
199  5.67  111             69
232  5.85  114             68
180  8.04   89             48

In [21]:
y

0      0
1      0
2      0
3      0
4      0
      ..
295    0
296    0
297    1
298    1
299    0
Name: placed, Length: 300, dtype: int64

In [22]:
df

     cgpa   iq  profile_score  placed
0    5.97  106             61       0
1    6.83  113             77       0
2    6.60  110             61       0
3    5.54  113             68       0
4    6.84  102             67       0
..    ...  ...            ...     ...
295  6.44  107             54       0
296  6.09  108             52       0
297  7.68  101             70       1
298  7.00   90             28       1
299  4.79  118             70       0

[300 rows x 4 columns]

In [24]:
model.predict([[4,106,61]])

C:\Users\91957\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

array([0], dtype=int64)

In [26]:
df['iq'].min() , df['iq'].max()

(83, 121)

In [28]:
df['profile_score'].min(), df['profile_score'].max()

(23, 100)